/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9ff",
        "surface-dim": "#cfdaf1",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d8e3fa",
        "on-surface": "#111c2c",
        "on-surface-variant": "#44464e",
        "inverse-surface": "#263142",
        "inverse-on-surface": "#ebf1ff",
        outline: "#75777f",
        "outline-variant": "#c5c6cf",
        "surface-tint": "#4c5e86",
        primary: "#00081e",
        "on-primary": "#ffffff",
        "primary-container": "#0a1f44",
        "on-primary-container": "#7687b2",
        "inverse-primary": "#b4c6f4",
        secondary: "#795900",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffc641",
        "on-secondary-container": "#715300",
        tertiary: "#070a0a",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1e2122",
        "on-tertiary-container": "#868889",
        error: "#ba1a1a",
        background: "#f9f9ff",
        "on-background": "#111c2c",
        "brand-gold": "#D4A017",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        gutter: "24px",
        unit: "8px",
      },
      fontFamily: {
        display: ["Montserrat", "sans-serif"],
        headline: ["Montserrat", "sans-serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["Work Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        ambient: "0 18px 50px rgba(0, 8, 30, 0.1)",
        "ambient-lg": "0 24px 70px rgba(0, 8, 30, 0.14)",
      },
      gridTemplateColumns: {
        desktop: "repeat(12, minmax(0, 1fr))",
        tablet: "repeat(8, minmax(0, 1fr))",
      },
    },
  },
  plugins: [],
};
